name_list = [
["Alan", "People Names", true, true, "Adrogynous"],
["Archibald", "People Names", true, true, "'Archie' for short"],
["Arnold","People Names",  true, false, "'Arnie' for short"],
["Beatrix", "People Names", false, true, "'Bea' for short"],
["Barbara", "People Names", false, true, "'Barb' or 'Barbie' for short"],
['Becky', "People Names", false, true, "Oh Becky!"],
["Birdie", "People Names", false, true, "'Birdi' is another option for spelling"],
["Bob", "People Names", true, false, "'Bobby' or 'Robert' could work too"], 
["Bucky", "People Names", true, false, "'Buckshot' or 'Buck"], 
["Darla", "People Names", false, true, "or Darlene"],
["Dennis", "People Names", true, false, "The Menace"],
["Dolly", "People Names", false, true, "Who is cuter than Dolly Parton?"],
["Dorothy", "People Names", false, true, "The Wizard of Oz"],
["Edward", "People Names", true, true, "'Eddie' or 'Ed'"],
["Edie", "People Names", false, true, "Pronounced 'Eeeee-D'"],
["Edna", "People Names", false, true, "Like Mrs. Krabappel from The Simpsons!"],
["Emerald", "People Names", false, true, "Also a stone and a Thin Lizzy song."],
["Estelle", "People Names", false, true, "Like the lovely Estelle Getty. Stella is also a classic."],
["Ethelle", "People Names", false, true, "Please name your pet this."],
["Faye", "People Names", false, true, "Or 'Fey'"],
["Fern", "People Names", false, true, "A great add on or middle name for a pup or kitty. Also a plant."],
["Frank", "People Names", true, true, "'Francis', 'Fran', 'Frankie'"],
["Gilda", "People Names", false, true, "The good witch!"],
["Grandma", "People Names", false, true, "Everybody loves Grandma. Especially King Diamond."],
["Grandpa", "People Names", true, false, "or 'Grampa'"],
["Herman", "People Names", true, false, "Munster"],
["Janet", "People Names", true, false, "I once knew a rabbit named Janet"],
["Jocepe", "People Names", true, false, "Fun to say. Spelling may be wrong."],
["Joe", "People Names", true, true, "Real Average. 'Joseph' or 'Jo'"],
["Judy", "People Names", false, true, "Judy is slang for a good pal."],
["Lorraine", "People Names", false, true, "A region in France. Also, 'Lori' or 'Lory'."],
["Loretta", "People Names", false, true, "Loretta Lynn"],
["Lucille", "People Names", false, true, "'Lucille, you won't do your Sisters' will?'"],
["Max", "People Names", true, true, "Maxine, Maximus, Maxwell..."],
["Morty", "People Names", true, false, "Short for 'Mortimer'"],
["Pam", "People Names", false, true, "Short for 'Pamela' or just 'Pam'"],
["Ralph", "People Names", true, false, "'My cat's breath smells like catfood.'"],
["Robert", "People Names", true, false, "'Bob', 'Bobby', 'Rob', 'Robbie'... goes well with a middlename."],
["Roberta", "People Names", false, true, "*also see 'Robert'"],
["Ruby", "People Names", false, true, " "],
["Sally", "People Names", false, true, " "],
["Seamous","People Names", true, false, " "]
["Sherman", "People Names", true, false, " "],
["Sharon", "People Names", false, true, " "],
["Steve", "People Names", true, false, " "],
["Steven", "People Names", true, false, "... or 'Steve'... or 'Stevie'."],
["Sylvia", "People Names", false, true, "Plath"],
["Tammy", "People Names", false, true, "Oh Tammy!"],
["Thomas", "People Names", true, false, "So formal."],
["Victor", "People Names", true, false, "'Vick'"],
["Wanda", "People Names", false, true, "Maybe for a fish?"],
["Wilma", "People Names", false, true, "Great with a middle name."],
["Blanche", "People Names", false, true, "Thank you for being a friend."],
["Dorthy", "People Names", false, true, "Thank you for being a friend."],
["Rose", "People Names", false, true, "Thank you for being a friend."] ,
["Sophia", "People Names", false, true, "Thank you for being a friend."],
["Aria", "Fictional Characters", false, true, "GOT"],
["Barbarella", "Fictional Characters", false, true, "'Barb', 'Barbie','Barbara'"],
["Beavis", "Fictional Characters", true, false, "You can’t name your pet 'Butthead', I’m sorry."], 
["Beatrix", "Fictional Characters", false, true, "Kill Bill"],
["Beaker", "Fictional Characters", true, true, "All Muppet names are good pet names."],
["Beetle Juice","Fictional Characters", true, false, "I am sure some cute nicknames could come of this."],
["Bill", "Fictional Characters", true, false, "...and Ted"] 
["Ted", "Fictional Characters", true, false, "Bill and ..."]
["Brad", "Fictional Characters", true, false, "'Dammit Janet.'"],
["Church","Fictional Characters", true, false, " aka Winston Churchill"],
["Columbia","Fictional Characters"],
["Cowboy Curtis", "Fictional Characters", true, false,] , 
["Cujo", "Fictional Characters", true, false,],
["Data", "Fictional Characters", true, false, ],
["Doctor Frankenfurter", "Fictional Characters", true, false,] ,
["Dottie", "Fictional Characters", false, true],
["Figaro", "Fictional Characters", false, true],
["Fraggle", "Fictional Characters", false, true],
["Fozzy", "Fictional Characters", false, true],
["Hodor", "Fictional Characters", true, false,],
["Immortan Joe", "Fictional Characters", true, false,] ,
["Janet", "Fictional Characters", false, true],
["Johnny Utah", "Fictional Characters", true, false,] ,
["Jones", "Fictional Characters", false, true ] ,
["Kermit", "Fictional Characters", true, false,],
["Leather Tuscadero", "Fictional Characters", false, true] ,
["Lord Humongous", "Fictional Characters", true, false,] ,
["Mad Max", "Fictional Characters", true, false,] ,
["Magenta", "Fictional Characters", false, true],
["Mavis Beacon", "Fictional Characters", false, true] ,
["Ms.Evone","Fictional Characters", false, true, "The most beautful woman in the world."], 
["Pascow", "Fictional Characters", true, false,],
["Pewee", "Fictional Characters", true, false,],
["Pancho", "Fictional Characters", true, false,] 
["Lefty", "Fictional Characters", true, false,],
["Rick", "Fictional Characters", true, false,],
["Riff Raff", "Fictional Characters", true, false,] ,
["Ripley", "Fictional Characters", false, true] ,
["Teddy Ruxpin", "Fictional Characters", true, false, "'Ruxpin' for short"] ,
["Toe Cutter", "Fictional Characters", true, false,] ,
["Warchild", "Fictional Characters", true, false,],
["Wayne" "and Garth", "Fictional Characters", true, false,],
["Garth","Fictional Characters", true, false,]
["Ziggy Stardust", "Fictional Characters", true, false,] ,
["Zoltan","Fictional Characters", true, false,],


["Banana", "Food and Drink"],
["Blue Berry", "Food and Drink"], 
["Booberry", "Food and Drink"],
["Burger", "Food and Drink"],
["Chaco Taco", "Food and Drink"] , 
["Chalula", "Food and Drink"],
["Chicken", "Food and Drink"],
["Chip", "Food and Drink"],
["Count Chocula", "Food and Drink"] ,
["Crinkle Cut", "Food and Drink"] ,
["Crispy", "Food and Drink"],
["Dolma", "Food and Drink"],
["Doughnut", "Food and Drink"],
["Fiddle Faddle", "Food and Drink"],
["FlapJack(s)", "Food and Drink"],
["Garbanzo", "Food and Drink"],
["Kale", "Food and Drink"],
["Mamba", "Food and Drink"],
["Nacho", "Food and Drink"],
["Pasta", "Food and Drink"],
["Pancake(s)", "Food and Drink"],
["Peppermint", "Food and Drink"],
["Pickle", "Food and Drink"],
*["Pigeon", "Food and Drink"]),
["Pizza", "Food and Drink"],
["Potato", "Food and Drink"] ,
["Ravioli", "Food and Drink"],
["Razberry", "Food and Drink"],
["Taco", "Food and Drink"],
["Tim Tam", "Food and Drink"] ,
["Tomato", "Food and Drink"],
["Trailmix", "Food and Drink"],
["Topo Chico", "Food and Drink"],
["Torta", "Food and Drink"],
["Waffles", "Food and Drink"],

["Cfa", "Nonsensical", true, true, "C for Cat"],
["Wiggle", "Nonsensical", "...and Fidget"],
["Nono", "Nonsensical"],
["Sari Mauve", "Nonsensical"],
["Jumanji", "Nonsensical"],
["Cabo Wabo", "Nonsensical"],
["Booger", "Nonsensical"],
["Tuk Tuk", "Nonsensical"],
["Widjet", "Nonsensical"],
["Chuco", "Nonsensical"],
["ChooChoo", "Nonsensical"]
["Pencil","Nonsensical"],
["Trumpet", "Nonsensical"], 
["Room 8", "Nonsensical"],
["Trex (T-ReX)", "Nonsensical"],
["Dander", "Nonsensical"],
["Dander Devito", "Nonsensical"],
["Zamboni", "Nonsensical"],



["Omega"],
["Freki"],
["Cowboy"], 
["Fenriz", "Alternative"],
["Pirate"],
["Comando"],
["Elvira", "Alternative"],
["Kevin"],
["Mark "],
["Bomber "],
["Blinko"],






["Crowley", "Famous People"],
["Faulkner", "Famous People"],
["Kitty Purry", "Famous People"],
["Poe", "Famous People"],
["Prince", "Famous People"],
["Reba", "Famous People"],
["Temple", "Famous People"],
["Tesla", "Famous People"],
["Tupac", "Famous People"],


["Hellhammer", "Alternative"],
["Mantis", "Alternative"],
["Cronos", "Alternative"],
["Abadon", "Alternative"],
["Beherit""Alternative"],
["Halford", "Alternative"],
["Tom G Warrior", "Alternative"], 
["Warlock", "Alternative"],
["Pantera", "Alternative"],
 ["Sid Vicious", "Alternative"],
["Glen", "Alternative"],
["KK Browning", "Alternative"],
["Ulver", "Alternative"],
["Rollins", "Alternative"],
["Uli", "Alternative"],
["Udo", "Alternative"],
["Mr. Crowley", "Alternative"],
["Ozzy", "Alternative"],
["Bones", "Alternative"],
["Black Flag", "Alternative"],
["Paintbox", "Alternative"],
["Midnight", "Alternative","For a white cat or dog...don’t be basic"], 
["Blacky", "Alternative"],
["Lawless", "Alternative"],
["Blacky Lawless", "Alternative"],
["Leather", "Alternative"],
["Doro", "Alternative"] ,
["Danzig","Alternative"],


["Arrow", "New Age"],
["Hex", "New Age"],
["Jex", "New Age"],
["Toth", "New Age"],
["Tarot", "New Age"],
["Hoodoo", "New Age"],
["Voodoo", "New Age"],
["Kali Ma", "New Age"], 
["Gypsy", "New Age"],


["Laika", true, true, "Famous Animals"],
["Sputnik", "Famous Animals"],
["Towser", "Famous Animals"],
["Pooli", "Famous Animals"],
["Room8", "Famous Animals"] 



["Worm", "Animals"],
["Chicken", "Animals"], 
["Pigeon", "Animals"],
["Mouse", "Animals"], 
["Moose", "Animals"],
["Goat", "Animals"],
["Goose", "Animals"],
["Pig", "Animals"],
["Raven", "Animals"],
["Possum", "Animals"],
["Spider", "Animals"],
["Butterfly", "Animals"],



["Banshee", "Mythical Creatures"],
["Warlock", "Mythical Creatures"],
["Satan", "Mythical Creatures"],
["Troll", "Mythical Creatures"],



["Osito", "International"],
["Silje", "International"],
["Guttorm", "International", true, false, "Boy worm in Norwegian"], 
["Kyrre", "International"],
["Sondre", "International"],
["Runar", "International"],
["Bjorn"] ,
["Torfinn"],
["Hallgeir"],
["Tromod"],
["Halvdan"],
["Sondre"],
["Asbjorn"],
["Ragnar"],
["Bard"],
["Stale"], 
["Sigmund"],
["Snorre"],
["Malfrid"], 
["Roja"],
["Solveig"],
["Gerd"],
["Aud"],
["Turid"],
["Reidun"],
["Oda"],
["Ingeborg"],
["Sigrid"],
["Vilde"],
["Vidis"],
["Sonja"],
["Solfrid"],
["Solvi"],
["Hildur"],
["Gjertrud"],
["Audhild"],


["Dahlia","Plants and Flowers"],
["Fern", "Plants and Flowers"] ,
["Huckleberry", "Plants and Flowers"],
["Begonia", "Plants and Flowers"],
["Lily", "Plants and Flowers"],
["Daffodil", "Plants and Flowers"],


["Ouija", "Spooky Stuff"],
["Tarot", "Spooky Stuff"],
["Ghost", "Spooky Stuff"],
["Dahmer", "Spooky Stuff"],
["Ramirez", "Spooky Stuff"],
["Krueger", "Spooky Stuff"],
["Vorhees", "Spooky Stuff"],
["Hoodoo", "Spooky Stuff"],
["Voodoo", "Spooky Stuff"],
["Zombie", "Spooky Stuff"],
["Goblin", "Spooky Stuff"],
["Boglin", "Spooky Stuff"],
["Nilbog", "Spooky Stuff"],
["Ghoulie", "Spooky Stuff"],
["Phantom", "Spooky Stuff"],
["Piano", "Instruments"],
["Banjo", "Instruments"],
["Trumpet", "Instruments"],
["Tuba", "Instruments"],
["Trombone", "Instruments"],

]



name_list.each do |name, category, male, female, comment|
  Name.create(name: name, category: category, male: male, female: female, comment:comment)
end

p "Created #{Name.count} names"