name_list = [
["Alan", "People Names", true, true, "Adrogynous"],
["Archibald", "People Names", true, true, "'Archie' for short"],
["Arnold","People Names",  true, false, "'Arnie' for short"],
["Beatrix", "People Names", false, true, "'Bea' for short"],
["Barbara", "People Names", false, true, "'Barb' or 'Barbie' for short"],
['Becky', "People Names", false, true, "Oh Becky!"],
["Birdie", "People Names", false, true, "'Birdi' is another option for spelling"],
["Bob", "People Names", true, false, "'Bobby' or 'Robert' could work too"], 
["Bucky", "People Names", true, false, "'Buckshot' or 'Buck"], 
["Darla", "People Names", false, true, "or Darlene"],
["Dennis", "People Names", true, false, "The Menace"],
["Dolly", "People Names", false, true, "Who is cuter than Dolly Parton?"],
["Dorothy", "People Names", false, true, "The Wizard of Oz"],
["Edward", "People Names", true, true, "'Eddie' or 'Ed'"],
["Edie", "People Names", false, true, "Pronounced 'Eeeee-D'"],
["Edna", "People Names", false, true, "Like Mrs. Krabappel from The Simpsons!"],
["Emerald", "People Names", false, true, "Also a stone and a Thin Lizzy song."],
["Estelle", "People Names", false, true, "Like the lovely Estelle Getty. Stella is also a classic."],
["Ethelle", "People Names", false, true, "Please name your pet this."],
["Faye", "People Names", false, true, "Or 'Fey'"],
["Fern", "People Names", false, true, "A great add on or middle name for a pup or kitty. Also a plant."],
["Frank", "People Names", true, true, "'Francis', 'Fran', 'Frankie'"],
["Gilda", "People Names", false, true, "The good witch!"],
["Grandma", "People Names", false, true, "Everybody loves Grandma. Especially King Diamond."],
["Grandpa", "People Names", true, false, "or 'Grampa'"],
["Herman", "People Names", true, false, "Munster"],
["Janet", "People Names", true, false, "I once knew a rabbit named Janet"],
["Jocepe", "People Names", true, false, "Fun to say. Spelling may be wrong."],
["Joe", "People Names", true, true, "Real Average. 'Joseph' or 'Jo'"],
["Judy", "People Names", false, true, "Judy is slang for a good pal."],
["Lorraine", "People Names", false, true, "A region in France. Also, 'Lori' or 'Lory'."],
["Loretta", "People Names", false, true, "Loretta Lynn"],
["Lucille", "People Names", false, true, "'Lucille, you won't do your Sisters' will?'"],
["Max", "People Names", true, true, "Maxine, Maximus, Maxwell..."],
["Morty", "People Names", true, false, "Short for 'Mortimer'"],
["Pam", "People Names", false, true, "Short for 'Pamela' or just 'Pam'"],
["Ralph", "People Names", true, false, "'My cat's breath smells like catfood.'"],
["Robert", "People Names", true, false, "'Bob', 'Bobby', 'Rob', 'Robbie'... goes well with a middlename."],
["Roberta", "People Names", false, true, "*also see 'Robert'"],
["Ruby", "People Names", false, true, " "],
["Sally", "People Names", false, true, " "],
["Seamous","People Names", true, false, " "]
["Sherman", "People Names", true, false, " "],
["Sharon", "People Names", false, true, " "],
["Steve", "People Names", true, false, " "],
["Steven", "People Names", true, false, "... or 'Steve'... or 'Stevie'."],
["Sylvia", "People Names", false, true, "Plath"],
["Tammy", "People Names", false, true, "Oh Tammy!"],
["Thomas", "People Names", true, false, "So formal."],
["Victor", "People Names", true, false, "'Vick'"],
["Wanda", "People Names", false, true, "Maybe for a fish?"],
["Wilma", "People Names", false, true, "Great with a middle name."],
["Blanche", "People Names", false, true, "Thank you for being a friend."],
["Dorthy", "People Names", false, true, "Thank you for being a friend."],
["Rose", "People Names", false, true, "Thank you for being a friend."] ,
["Sophia", "People Names", false, true, "Thank you for being a friend."],
["Kevin", "People Names", true, true, "Androgynous"],
["Mark", "People Names", true, false, "Just Mark"],
["Aria", "Fictional Characters", false, true, "GOT"],
["Barbarella", "Fictional Characters", false, true, "'Barb', 'Barbie','Barbara'"],
["Beavis", "Fictional Characters", true, false, "You can’t name your pet 'Butthead', I’m sorry."], 
["Beatrix", "Fictional Characters", false, true, "Kill Bill"],
["Beaker", "Fictional Characters", true, true, "All Muppet names are good pet names."],
["Beetle Juice","Fictional Characters", true, false, "I am sure some cute nicknames could come of this."],
["Bill", "Fictional Characters", true, false, "...and Ted"] 
["Ted", "Fictional Characters", true, false, "Bill and ..."]
["Brad", "Fictional Characters", true, false, "'Dammit Janet.'"],
["Church","Fictional Characters", true, false, " aka Winston Churchill"],

["Columbia","Fictional Characters", false, true, "Rocky Horror"],
["Cowboy Curtis", "Fictional Characters", true, false, "The coolest role Laurence Fishburne ever played. Convince me otherwise."] , 
["Cujo", "Fictional Characters", true, false, "Classic but scary"],
["Data", "Fictional Characters", true, false, "Star Trek" ],
["Doctor Frankenfurter", "Fictional Characters", true, false, "Great weiner dog name."] ,
["Dottie", "Fictional Characters", false, true, "'I'm a loner Dottie, a rebel.'"],
["Figaro", "Fictional Characters", true, true, "Pinocchio"],
["Fraggle", "Fictional Characters", true, true, "All Muppet names are good pet names."],
["Fozzy", "Fictional Characters", false, true, "All Muppet names are good pet names."],
["Hodor", "Fictional Characters", true, false,],
["Immortan Joe", "Fictional Characters", true, false,] ,
["Janet", "Fictional Characters", false, true],
["Johnny Utah", "Fictional Characters", true, false,] ,
["Jones", "Fictional Characters", false, true ] ,
["Kermit", "Fictional Characters", true, false, "All Muppet names are good pet names."],
["Leather Tuscadero", "Fictional Characters", false, true] ,
["Lord Humongous", "Fictional Characters", true, false,] ,
["Mad Max", "Fictional Characters", true, false,] ,
["Magenta", "Fictional Characters", false, true],
["Mavis Beacon", "Fictional Characters", false, true] ,
["Ms.Evone","Fictional Characters", false, true, "The most beautful woman in the world."], 
["Pascow", "Fictional Characters", true, false,],
["Pewee", "Fictional Characters", true, false,],
["Pancho", "Fictional Characters", true, false,] 
["Lefty", "Fictional Characters", true, false,],
["Rick", "Fictional Characters", true, false,],
["Riff Raff", "Fictional Characters", true, false,] ,
["Ripley", "Fictional Characters", false, true] ,
["Teddy Ruxpin", "Fictional Characters", true, false, "'Ruxpin' for short"] ,
["Toe Cutter", "Fictional Characters", true, false,] ,
["Warchild", "Fictional Characters", true, false,],
["Wayne" "and Garth", "Fictional Characters", true, false,],
["Garth","Fictional Characters", true, false,]
["Ziggy Stardust", "Fictional Characters", true, false,] ,
["Zoltan","Fictional Characters", true, false,],
["Banana", "Food and Drink", true, true, ],
["Blue Berry", "Food and Drink", true, true,], 
["Booberry", "Food and Drink", true, true,],
["Burger", "Food and Drink", true, true,],
["Chaco Taco", "Food and Drink", true, true,] , 
["Chalula", "Food and Drink", true, true,],
["Chicken", "Food and Drink", true, true,],
["Chip", "Food and Drink", true, true,],
["Count Chocula", "Food and Drink", true, true,] ,
["Crinkle Cut", "Food and Drink", true, true,] ,
["Crispy", "Food and Drink", true, true,],
["Dolma", "Food and Drink", true, true,],
["Doughnut", "Food and Drink", true, true,],
["Fiddle Faddle", "Food and Drink", true, true,],
["FlapJack(s)", "Food and Drink", true, true,],
["Garbanzo", "Food and Drink", true, true,],
["Kale", "Food and Drink", true, true,],
["Mamba", "Food and Drink", true, true,],
["Nacho", "Food and Drink", true, true,],
["Pasta", "Food and Drink", true, true,],
["Pancake(s)", "Food and Drink", true, true,],
["Peppermint", "Food and Drink", true, true,],
["Pickle", "Food and Drink", true, true,],
*["Pigeon", "Food and Drink", true, true,]),
["Pizza", "Food and Drink", true, true,],
["Potato", "Food and Drink", true, true,] ,
["Ravioli", "Food and Drink", true, true,],
["Razberry", "Food and Drink", true, true,],
["Taco", "Food and Drink", true, true,],
["Tim Tam", "Food and Drink", true, true,] ,
["Tomato", "Food and Drink", true, true,],
["Trailmix", "Food and Drink", true, true,],
["Topo Chico", "Food and Drink", true, true,],
["Torta", "Food and Drink", true, true,],
["Waffles", "Food and Drink", true, true,],
["Cfa", "Nonsensical", true, true, "C for Cat"],
["Wiggle", "Nonsensical", true, true, "...and Fidget"],
["Nono", "Nonsensical", true, true, "I wish I would have named my cat 'Bad Man NoNo'"],
["Sari Mauve", "Nonsensical", false, true, "This is my cat's name. I don't know what it means. Her previous owner made it up."],
["Jumanji", "Nonsensical", true, true,],
["Cabo Wabo", "Nonsensical", true, true,],
["Booger", "Nonsensical", true, true,],
["Tuk Tuk", "Nonsensical", true, true,],
["Widjet", "Nonsensical", true, true,],
["Chuco", "Nonsensical", true, true,],
["ChooChoo", "Nonsensical", true, true,]
["Pencil","Nonsensical", true, true,],
["Trumpet", "Nonsensical", true, true,], 
["Room 8", "Nonsensical", true, true,],
["Trex (T-ReX)", "Nonsensical", true, true,],
["Dander", "Nonsensical", true, true,],
["Dander Devito", "Nonsensical", true, false,],
["Zamboni", "Nonsensical", true, true,],



["Omega","Random", true, true, ],
["Cowboy", "Random", true, true,], 
["Fenriz", "Alternative"],
["Pirate", "Random", true, true,],
["Comando", "Random", true, false,],


["Bomber", "Random", true, true, "Motorhead or Girlschool"],
["Blinko", "Alternative", true, true, "Nick"],
["Crowley", "Famous People", true, true, "'Aleister' or 'Mr. Crowley'"],
["Faulkner", "Famous People", true, false, "'William'"],
["Kitty Purry", "Famous People", false, true, "(Katie Perry)"],
["Poe", "Famous People", true, true, "Edgar Allen"],
["Prince", "Famous People", true, true "Needs a purple collar."],
["Reba", "Famous People", false, true, "'Fancy'"],
["Temple", "Famous People", false, true, "'Grandin'"],
["Tesla", "Famous People", true, false, "Not the car. Elon could be a cool name tho."],
["Tupac", "Famous People", true, false, "Respect."],


["Hellhammer", "Alternative",true, true, "Tom Warrior"],
["Mantis", "Alternative", true, false, "Venom"],
["Cronos", "Alternative", true, false, "Venom"],
["Abadon", "Alternative", true, false, "Venom"],
["Beherit","Alternative", true, true, "Evil AF".],
["Halford", "Alternative", true, false, "Rob Halford would be so stoked if you named your cat this."],
["Tom G Warrior", "Alternative", true, false], 
["Warlock", "Alternative",true, false, "Like the bad or the sorcerer"],
["Pantera", "Alternative", true, true, "Panther in Spanish or the 90's metal band"],
["Sid Vicious", "Alternative", true, true, "Punk af."],
["Elvira", "Alternative", false, true, "Mistress of the Dark"],
["Glen Tipton", "Alternative", true, false, "Friends with KK Browning."],
["KK Browning", "Alternative", true, false, "Friends with Glen Tipton"],
["Ulver", "Alternative", true, false, "'wolf howls in the background'"],
["Rollins", "Alternative", true, false, "HANK!"],
["Uli", "Alternative", true, false, "Scorpions"],
["Udo", "Alternative", true, false, "Accept"],
["Mr. Crowley", "Alternative", true, false, "Classic Ozzy song"],
["Ozzy", "Alternative", true, false, "Osbourne"],
["Bones", "Alternative", true, true, "Classic punk dog name."],
["Black Flag", "Alternative", true, true,"Pet owner must have corresponding tattoo"],
["Paintbox", "Alternative", true, false, "For fans of Japanese Hardcore and a really sweet weiner dog I once knew."],
["Midnight", "Alternative", true, true, "For a white cat or dog...don’t be basic"], 
["Blacky Lawless", "Alternative", true, false, "A very specific looking pet needs this name."],
["Leather", "Alternative", false, true, "Tuscadero or Leone"],
["Doro", "Alternative", false, true, "The Queen of Heavy Metal."] ,
["Danzig","Alternative", true, false, "'Glen' for short. haha"],


["Arrow", "New Age"],
["Hex", "New Age"],
["Jex", "New Age"],
["Toth", "New Age"],
["Tarot", "New Age"],
["Hoodoo", "New Age"],
["Voodoo", "New Age"],
["Kali Ma", "New Age"], 
["Gypsy", "New Age"],


["Laika", true, true, "Famous Animals"],
["Sputnik", "Famous Animals"],
["Towser", "Famous Animals"],
["Pooli", "Famous Animals"],
["Room8", "Famous Animals"] 



["Worm", "Animals"],
["Chicken", "Animals"], 
["Pigeon", "Animals"],
["Mouse", "Animals"], 
["Moose", "Animals"],
["Goat", "Animals"],
["Goose", "Animals"],
["Pig", "Animals"],
["Raven", "Animals"],
["Possum", "Animals"],
["Spider", "Animals"],
["Butterfly", "Animals"],



["Banshee", "Mythical Creatures", false, true, "Woman of the faeries"],
["Warlock", "Mythical Creatures", true, false, "A man who practices witchcraft; a sorcerer."],
["Satan", "Mythical Creatures", true, true, "A surprisingly popular pet name."],
["Troll", "Mythical Creatures", true, true, "A mythical, cave-dwelling being depicted in folklore as either a giant or a dwarf, typically having a very ugly appearance."],
["Freki", "Mythical Creatures", true, true, "Old Norse, both meaning 'the ravenous' or 'greedy one'"],




["Osito", "International"],
["Silje", "International"],
["Guttorm", "International", true, false, "Boy worm in Norwegian"], 
["Kyrre", "International"],
["Sondre", "International"],
["Runar", "International"],
["Bjorn", "International"] ,
["Torfinn", "International"],
["Hallgeir", "International"],
["Tromod", "International"],
["Halvdan", "International"],
["Sondre", "International"],
["Asbjorn", "International"],
["Ragnar", "International"],
["Bard", "International"], 
["Sigmund", "International"],
["Snorre", "International"],
["Malfrid", "International"], 
["Roja", "International"],
["Solveig", "International"],
["Gerd", "International"],
["Aud", "International"],
["Turid", "International"],
["Reidun", "International"],
["Oda", "International"],
["Ingeborg", "International"],
["Sigrid", "International"],
["Vilde", "International"],
["Vidis", "International"],
["Sonja", "International"],
["Solfrid", "International"],
["Solvi", "International"],
["Hildur", "International"],
["Gjertrud", "International"],
["Audhild"], "International",


["Dahlia","Plants and Flowers"],
["Fern", "Plants and Flowers"] ,
["Huckleberry", "Plants and Flowers"],
["Begonia", "Plants and Flowers"],
["Lily", "Plants and Flowers"],
["Daffodil", "Plants and Flowers"],


["Ouija", "Spooky Stuff"],
["Tarot", "Spooky Stuff"],
["Ghost", "Spooky Stuff"],
["Dahmer", "Spooky Stuff"],
["Ramirez", "Spooky Stuff"],
["Krueger", "Spooky Stuff"],
["Vorhees", "Spooky Stuff"],
["Hoodoo", "Spooky Stuff"],
["Voodoo", "Spooky Stuff"],
["Zombie", "Spooky Stuff"],
["Goblin", "Spooky Stuff"],
["Boglin", "Spooky Stuff"],
["Nilbog", "Spooky Stuff"],
["Ghoulie", "Spooky Stuff"],
["Phantom", "Spooky Stuff"],
["Piano", "Instruments"],
["Banjo", "Instruments"],
["Trumpet", "Instruments"],
["Tuba", "Instruments"],
["Trombone", "Instruments"],

name_list.each do |name, category, male, female, comment|
  Name.create(name: name, category: category, male: male, female: female, comment:comment)
end

p "Created #{Name.count} names"