name_list = [
  
["Alan", "People Names", true, true, "none"],
["Archibald", "People Names", true, true, "'Archie' for short"],
["Arnold","People Names",  true, false, "'Arnie' for short"],
["Beatrix", "People Names", false, true, "'Bea' for short"],
["Barbara", "People Names", false, true, "'Barb' or 'Barbie' for short"],
['Becky', "People Names", false, true, "Oh Becky!"],
["Birdie", "People Names", false, true, "'Birdi' is another option for spelling"],
["Bob", "People Names", true, false, "'Bobby' or 'Robert' could work too"], 
["Bucky", "People Names", true, false, "'Buckshot' or 'Buck"], 
["Darla", "People Names",],
["Dennis", "People Names",],
["Dolly", "People Names"] ,
["Dorothy", "People Names"],
["Edward", "People Names", "Eddie"]
["Edie", "People Names"],
["Edna", "People Names"],
["Emerald"],
["Estelle"],
["Ethelle"],
["Faye"],
["Fern"],
["Frank"],
["Gilda"],
["Grandma"],
["Grandpa"],
["Herman"],
["Janet"],
["Jocepe"],
["Joe"],
["Joseph"],
["Judy"],
["Lorraine"],
["Loretta"],
["Lucille"],
["Max"],
*["Morty"],
["Pam"],
*["Ralph"],
["Robert"],
["Roberta"],
["Ruby"],
["Sally"],
["Seamous",]
["Sherman"],
["Sharon"],
["Steve"],
["Steven"],
["Sylvia"],
["Tammy"],
["Thomas"],
["Victor"],
["Wanda"],
["Wilma"],

["Blanche"],
["Dorthy"],
["Rose"] ,
["Sophia"],


["Aria", "Fictional Characters", false, true, "GOT"],
["Barbarella", "Fictional Characters"],
["Beavis", "Fictional Characters", true, false, "You can’t name your pet 'Butthead', I’m sorry."], 
["Beatrix", "Fictional Characters", false, true, "Kill Bill"],
["Beaker"],
["Beetle Juice"],
["Bill", "Fictional Characters", true, false, "...and Ted"] 
["Ted"]
["Brad"],
["Church","Fictional Characters", true, false, " aka Winston Churchill"],
["Columbia"],
["Cowboy Curtis"] , 
["Cujo"],
["Data"],
["Doctor Frankenfurter"] ,
["Dottie"],
["Figaro"],
["Fraggle"],
["Fozzy"],
["Hodor"],
["Immortan Joe"] ,
["Janet"],
["Johnny Utah"] ,
["Jones", ] ,
["Kermit"],
["Leather Tuscadero"] ,
["Lord Humongous"] ,
["Mad Max"] ,
["Magenta"],
["Master Beacon"] ,
["Mavis Beacon"] ,
["Morty"],
["Ms.Evone","Fictional Characters", false, true, "The most beautful woman in the world."], 
["Pascow"],
["Pewee"],
["Pancho"] 
["Lefty"],
["Rick"],
["Riff Raff"] ,
["Ripley"] ,
["Teddy Ruxpin", "'Ruxpin' for short"] ,
["Toe Cutter"] ,
["Warchild"],
["Wayne" "and Garth"],
["Garth"]
["Ziggy Stardust"] ,
["Zoltan"],


["Banana", "Food and Drink"],
["Blue Berry",], 
["Booberry"],
["Burger"],
["Chaco Taco"] , 
["Chalula"],
["Chicken"],
["Chip"],
["Count Chocula"] ,
["Crinkle Cut"] ,
["Crispy"],
["Dolma"],
["Doughnut"],
["Fiddle Faddle"],
["FlapJack(s)"],
["Garbanzo"],
["Kale"],
["Mamba"],
["Nacho"],
["Pasta"],
["Pancake(s)"],
["Peppermint"],
["Pickle"],
*["Pigeon"]),
["Pizza"],
["Potato"] ,
["Ravioli"],
["Razberry"],
["Taco"],
["Tim Tam"] ,
["Tomoatoe"],
["Trailmix"],
["Topo Chico"],
["Torta"],
["Waffles"],

["Cfa", "Nonsensical", true, true, "C for Cat"],
["Wiggle and Fidget"],
["Nono"],
["Sari Mauve"],
["Jumanji"],
["Cabo Wabo"],
["Booger"],
["Tuk Tuk"],
["Widjet "],
["Chuco"],
["ChooChoo,"]
["Pencil"],
["Trumpet"], 
["Room 8"],
["Trex (T-ReX)"],
["Dander"],
["Dander Devito"],
["Zamboni"],



["Omega"],
["Freki"],
["Cowboy"], 
["Fenriz"],
["Pirate"],
["Phantom"],
["Comando"],
["Elvira"],
["Kevin"],
["Mark "],
["Bomber "],
["Blinko"],






["Crowley", "Famous People"],
["Faulkner"],
["Kitty Purry"],
["Poe"],
["Prince"],
["Reba"],
["Temple"],
["Tesla"],
["Tupac"],


["Hellhammer", "Alternative"],
["Mantis"],
["Cronos"],
["Abadon"],
["Beherit"],
["Halford"],
["Tom G Warrior"], 
["Warlock"],
["Pantera"],
 ["Sid Vicious"],
["Glen"],
["KK Browning"],
["Ulver"],
["Rollins"],
["Uli"],
["Udo"],
["Mr. Crowley"],
["Ozzy"],
["Bones"],
["Black Flag"],
["Paintbox"],
["Midnight", "For a white cat or dog...don’t be basic"], 
["Blacky"],
["Lawless"],
["Blacky Lawless"],
["Leather"],
["Fenriz"],
["Doro"] ,
["Tesla"],
["Danzig"],


["Arrow", "New Age"],
["Hex"],
["Jex"],
["Toth"],
["Tarot"],
["Raja"],
["Majick",]
["Chakra"],
["Shakti"],,
["Deva"],
["Shiva"],
["Shakti"],
["Hoodoo"],
["Voodoo"],
["Kali Ma"], 
["Gypsy"],


["Laika","Famous Animals"],
["Sputnik"],
["Towser"],
["Pooli"],
["Room8"] 



["Worm", "Animals"],
["Chicken"], 
["Pigeon"],
["Mouse"], 
["Moose"],
["Goat"],
["Goose"],
["Pig"],
["Raven"],
["Possum"],
["Spider"],
["Butterfly"],



["Banshee" "Mythical Creatures"],
["Warlock"],
["Satan"],


["Osito", "International"],
["Silje"],
["Guttorm", "Boy worm in Norwegian"], 
["Kyrre"],
["Sondre"],
["Runar"],
["Bjorn"] ,
["Torfinn"],
["Hallgeir"],
["Tromod"],
["Halvdan"],
["Sondre"],
["Asbjorn"],
["Ragnar"],
["Bard"],
["Stale"], 
["Sigmund"],
["Snorre"],
["Malfrid"], 
["Roja"],
["Solveig"],
["Gerd"],
["Aud"],
["Turid"],
["Reidun"],
["Oda"],
["Ingeborg"],
["Sigrid"],
["Vilde"],
["Vidis"],
["Sonja"],
["Solfrid"],
["Solvi"],
["Hildur"],
["Gjertrud"],
["Audhild"],


["Dahlia","Plants and Flowers"],
["Fern"] ,
["Huckleberry"],
["Begonia"],
["Lily"],
["Daffodil"],


["Ouija", "Spooky Stuff"],
["Tarot"],
["Ghost"],
["Dahmer"],
["Ramirez"],
["Krueger"],
["Vorhees"],
["Hoodoo"],
["Voodoo"],

["Piano", "Instruments"],
["Banjo"],
["Trumpet"],
["Tuba"],
["Trombone"],

]